### ISSUE TITLE
Ruby 2.7

### ISSUE THREAD

**Issue by Hywan** [danielpclark/rutie#114]
Hello,

I tried to use rutie with Ruby 2.7 and it seems to fail. See the logs, https://github.com/wasmerio/ruby-ext-wasm/runs/481967739?check_suite_focus=true.

```
/home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fiddle.rb:47:in `initialize': libruby.so.2.6: cannot open shared object file: No such file or directory (Fiddle::DLError)
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fiddle.rb:47:in `new'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/fiddle.rb:47:in `dlopen'
	from /home/runner/.gem/gems/rutie-0.0.4/lib/rutie.rb:21:in `init'
	from /home/runner/work/ruby-ext-wasm/ruby-ext-wasm/lib/wasmer.rb:5:in `<module:Wasmer>'
	from /home/runner/work/ruby-ext-wasm/ruby-ext-wasm/lib/wasmer.rb:4:in `<top (required)>'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /home/runner/work/ruby-ext-wasm/ruby-ext-wasm/tests/prelude.rb:2:in `<top (required)>'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /home/runner/work/ruby-ext-wasm/ruby-ext-wasm/tests/global_test.rb:2:in `<top (required)>'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `select'
	from /home/runner/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1)
```

Is Rutie tested against Ruby 2.7 already, or is it something I've to check on my side?

Thanks!

**Comment by Zapotek** [comment]
Did you run `cargo clean` before recompiling your extension for Ruby 2.7?

**Comment by Hywan** [comment]
That’s a fresh installation, so yes, kind of :-).

**Comment by danielpclark** [comment]
I plan on getting to this when I get some free time.  Ruby 2.7 is the next target to update this for and getting Integers ranges fixed #113 is part of that.

**Comment by danielpclark** [comment]
I'm sorry I didn't pay more attention to you issue.  The problem is a simple fix by deleting the built source code with `rm -rf target`.  When switching Ruby versions you always need to deleted the previous build.  The other way to do it is to run `cargo clean`

**Comment by Hywan** [comment]
:+1: gonna try!
