### ISSUE TITLE
ERROR  about 'rb_num2uint' in win11 when compile the 'rutie_ruby_example'

### ISSUE THREAD

**Issue by ying911008** [danielpclark/rutie#184]
I run the example of 'rutie_ruby_example' in win11，but it can't work well.The following is an error message:

librutie-6ff32d813178a209.rlib(rutie-6ff32d813178a209.rutie.a5a323cc5a6857a9-cgu.4.rcgu.o) : error LNK2001: 无法解析的外部符号 rb_num2uint
          C:\rutie-master\examples\rutie_ruby_example\target\release\deps\rutie_ruby_example.dll : fatal error LNK1120: 1 个无法解析的外部命令

I checked the generated exports.txt, and it doesn't have the 'rb_num2uint', my ruby is 'ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x64-mingw32]'

**Comment by ying911008** [comment]
I use ruby3.0.0 do it again, it can work, and I get the rutie_ruby_example.dll, but run it width ruby, it can't  work well, the following is an error message:
 C:/Ruby-on-Windows/3.0.0-1/lib/ruby/gems/3.0.0/gems/rutie-0.0.4/lib/rutie.rb:21:in `call': wrong argument type Integer (expected Class) (TypeError)
        from C:/Ruby-on-Windows/3.0.0-1/lib/ruby/gems/3.0.0/gems/rutie-0.0.4/lib/rutie.rb:21:in `init'
